### PR TITLE
Third tutorial

### LINKED ISSUE #8: Write Tutorial about how to use Circles Account in Gnosis Safe App
**Todo:**

- [x] Merge tutorial PR
- [x] Integrate tutorial in navigation sidebar
- [x] Make images look nicer (maybe there is something in docusaurus one can just use)

Related discussion: https://aboutcircles.com/t/use-gnosis-safe-as-circles-wallet/338/11

### LINKED ISSUE #9: Write Tutorial about the general Circles system for developers
Integrate this article: https://www.sbt-ethereum.io/blog/2021/03/23/Circles-with-sbt-ethereum-II-Circles-by-hand-redux.html

### PR DESCRIPTION
**Pull request by louilinn**
PR fixes https://github.com/CirclesUBI/circles-handbook/issues/9 and fixes https://github.com/CirclesUBI/circles-handbook/issues/8

- [x] Reformat tutorial to markdown
- [x] Add tutorial(s) to sidebar
- [x] Collapse extensive code blocks
- [ ] Consider other changes to the tutorial in integrating it to the docusaurus website
- [x] Make images smaller / better in first two tutorials

### CODE REVIEW

**Comment by louilinn** [comment]
I changed the images in the tutorials as well, looked for different options but ended up using this: https://docusaurus.io/docs/markdown-features/react

Not sure if I should put that code for FormattedImage somewhere else if we decide to stick with this as it is now duplicated.

**Comment by adzialocha** [comment]
> Not sure if I should put that code for FormattedImage somewhere else if we decide to stick with this as it is now duplicated.

Let's move it to `/src/common/FormattedImage.js`!

**Review by llunaCreixent — DISMISSED** [review]
Super Nice Forntend work :)

**Review by adzialocha — APPROVED** [review]
:sparkles:

**Pull request merged**
